import {
  AirVent,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  BadgeCheck,
  Bell,
  BriefcaseBusiness,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  Clock3,
  CreditCard,
  Download,
  Droplets,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Hammer,
  Heart,
  HeartOff,
  House,
  Image,
  Info,
  LayoutDashboard,
  Leaf,
  Lock,
  LockOpen,
  LogOut,
  LucideIcon,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  NotebookText,
  Paintbrush,
  Pencil,
  Phone,
  Plus,
  Search,
  Settings,
  Share2,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Star,
  StarOff,
  Tags,
  Trash2,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  X,
  Zap,
} from 'lucide-react-native';

export const ICON_COMPONENTS = {
  'air-vent': AirVent,
  'alert': TriangleAlert,
  'appointment': Calendar,
  'arrow-back': ArrowLeft,
  'arrow-forward': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  'bell': Bell,
  'briefcase': BriefcaseBusiness,
  'calendar': Calendar,
  'camera': Camera,
  'check': Check,
  'cleaning': Sparkles,
  'coordination': MessageCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clock': Clock3,
  'close': X,
  'credit-card': CreditCard,
  'delete': Trash2,
  'document': FileText,
  'download': Download,
  'droplets': Droplets,
  'edit': Pencil,
  'electrical': Zap,
  'email': Mail,
  'error': X,
  'external-payment': Wallet,
  'eye': Eye,
  'eye-off': EyeOff,
  'filter': SlidersHorizontal,
  'flame': Flame,
  'hammer': Hammer,
  'heart': Heart,
  'heart-outline': HeartOff,
  'help': CircleHelp,
  'home': House,
  'image': Image,
  'info': Info,
  'layout-dashboard': LayoutDashboard,
  'leaf': Leaf,
  'location': MapPin,
  'lock': Lock,
  'logout': LogOut,
  'menu': Menu,
  'message': MessageCircle,
  'minus': Minus,
  'moving': BriefcaseBusiness,
  'notebook': NotebookText,
  'paint': Paintbrush,
  'phone': Phone,
  'plumbing': Droplets,
  'plus': Plus,
  'profile': User,
  'professional': BriefcaseBusiness,
  'proposal': FileText,
  'publish': Pencil,
  'rating': Star,
  'request': FileText,
  'review': Star,
  'search': Search,
  'settings': Settings,
  'share': Share2,
  'snowflake': Snowflake,
  'sort': ArrowUpDown,
  'sparkles': Sparkles,
  'star': Star,
  'star-outline': StarOff,
  'success': Check,
  'tags': Tags,
  'tool': Wrench,
  'unlock': LockOpen,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'verification': BadgeCheck,
  'wallet': Wallet,
  'warning': TriangleAlert,
  'wrench': Wrench,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_COMPONENTS;

export const isIconName = (value: string): value is IconName => value in ICON_COMPONENTS;

export const CATEGORY_ICON_NAMES: Record<string, IconName> = {
  electricidad: 'electrical',
  plomeria: 'plumbing',
  gas: 'flame',
  carpinteria: 'hammer',
  pintura: 'paint',
  jardineria: 'leaf',
  limpieza: 'cleaning',
  'aire-acondicionado': 'air-vent',
  default: 'tool',
};

export const getCategoryIconName = (slug?: string, icon?: string): IconName => {
  if (icon && isIconName(icon)) {
    return icon;
  }

  if (slug) {
    return CATEGORY_ICON_NAMES[slug] || CATEGORY_ICON_NAMES.default;
  }

  return CATEGORY_ICON_NAMES.default;
};
